
name: Tech Quiz - Develop Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  pull_request:
    branches:
      - Develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # The type of runner that the job will run on
  test-runner:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        uses: cypress-io/github-action@v2
        with: 
          build: npm run build
          start: npm run start
        #  component: true
